USE lab_mysql;

CREATE TABLE Cars (Id INT AUTO_INCREMENT PRIMARY KEY, VIN VARCHAR(20), 
Manufacturer VARCHAR(20), Model VARCHAR(20), Year INT4, Color VARCHAR(20));

CREATE TABLE Customers (Id INT AUTO_INCREMENT PRIMARY KEY, CustomerID VARCHAR(20), 
Name VARCHAR(20), Phone VARCHAR(20), Email VARCHAR(50), Address VARCHAR(100),
City VARCHAR(20));

CREATE TABLE salespersons (Id INT AUTO_INCREMENT PRIMARY KEY, StaffId VARCHAR(20), 
Name VARCHAR(20), Store VARCHAR(20));

CREATE TABLE invoices (Id INT AUTO_INCREMENT PRIMARY KEY, InvoiceNumber VARCHAR(20), 
Date DATE, CarId VARCHAR(20), CustomerId VARCHAR(20), StaffId VARCHAR(20));