CREATE DATABASE lab_mysql;
USE lab_mysql;
CREATE TABLE Cars (
VIN_ID VARCHAR(20),
MANUFACTURER VARCHAR(25), 
MODEL VARCHAR(25), 
YEAR INT(4), 
COLOUR VARCHAR(15)
);

CREATE TABLE Customer (
C_ID INT(10), 
NAME VARCHAR(25), 
PHONE_NUM VARCHAR(15), 
EMAIL VARCHAR(30), 
ADRESS VARCHAR(50), 
CITY VARCHAR (25), 
STATE VARCHAR(25),
COUNTRY VARCHAR(25), 
ZIP INT(8)
);

CREATE TABLE Sales_pers (
ST_ID VARCHAR(20), 
NAME VARCHAR (25), 
STORE VARCHAR(25)
);

CREATE TABLE Invoices (
IN_ID VARCHAR(20), 
DATE date, 
CAR_VIN VARCHAR(20), 
C_ID INT(10), 
ST_ID VARCHAR(20)
);
