#Seeding car manufacturers
INSERT INTO `Manufacturer` (`name`) VALUES ("BMW");
INSERT INTO `Manufacturer` (`name`) VALUES ("Buick");
INSERT INTO `Manufacturer` (`name`) VALUES ("Cadillac");
INSERT INTO `Manufacturer` (`name`) VALUES ("Chevrolet");
INSERT INTO `Manufacturer` (`name`) VALUES ("Chrysler");
INSERT INTO `Manufacturer` (`name`) VALUES ("Dodge");
INSERT INTO `Manufacturer` (`name`) VALUES ("Ferrari");
INSERT INTO `Manufacturer` (`name`) VALUES ("Ford");
INSERT INTO `Manufacturer` (`name`) VALUES ("GM");
INSERT INTO `Manufacturer` (`name`) VALUES ("GEM");
INSERT INTO `Manufacturer` (`name`) VALUES ("GMC");
INSERT INTO `Manufacturer` (`name`) VALUES ("Honda");
INSERT INTO `Manufacturer` (`name`) VALUES ("Hummer");
INSERT INTO `Manufacturer` (`name`) VALUES ("Hyundai");
INSERT INTO `Manufacturer` (`name`) VALUES ("Infiniti");
INSERT INTO `Manufacturer` (`name`) VALUES ("Isuzu");
INSERT INTO `Manufacturer` (`name`) VALUES ("Jaguar");
INSERT INTO `Manufacturer` (`name`) VALUES ("Jeep");
INSERT INTO `Manufacturer` (`name`) VALUES ("Kia");
INSERT INTO `Manufacturer` (`name`) VALUES ("Lamborghini");
INSERT INTO `Manufacturer` (`name`) VALUES ("Land Rover");
INSERT INTO `Manufacturer` (`name`) VALUES ("Lexus");
INSERT INTO `Manufacturer` (`name`) VALUES ("Lincoln");
INSERT INTO `Manufacturer` (`name`) VALUES ("Lotus");
INSERT INTO `Manufacturer` (`name`) VALUES ("Mazda");
INSERT INTO `Manufacturer` (`name`) VALUES ("Mercedes-Benz");
INSERT INTO `Manufacturer` (`name`) VALUES ("Mercury");
INSERT INTO `Manufacturer` (`name`) VALUES ("Mitsubishi");
INSERT INTO `Manufacturer` (`name`) VALUES ("Nissan");
INSERT INTO `Manufacturer` (`name`) VALUES ("Oldsmobile");
INSERT INTO `Manufacturer` (`name`) VALUES ("Peugeot");
INSERT INTO `Manufacturer` (`name`) VALUES ("Pontiac");
INSERT INTO `Manufacturer` (`name`) VALUES ("Porsche");
INSERT INTO `Manufacturer` (`name`) VALUES ("Regal");
INSERT INTO `Manufacturer` (`name`) VALUES ("Saab");
INSERT INTO `Manufacturer` (`name`) VALUES ("Saturn");
INSERT INTO `Manufacturer` (`name`) VALUES ("Subaru");
INSERT INTO `Manufacturer` (`name`) VALUES ("Suzuki");
INSERT INTO `Manufacturer` (`name`) VALUES ("Toyota");
INSERT INTO `Manufacturer` (`name`) VALUES ("Volkswagen");
INSERT INTO `Manufacturer` (`name`) VALUES ("Volvo");


#Seeding cars
INSERT INTO `Car` (`vehicle_identification_number`,`model`, `year`, `color`,`manufacturer_ID`) VALUES ("ZM8G7BEUQZ97IH46V", "Rifter", 2019, "Red", 124);
INSERT INTO `Car` (`vehicle_identification_number`,`model`, `year`, `color`,`manufacturer_ID`) VALUES ("RKXVNNIHLVVZOUB4M", "Fusion", 2018, "White", 101);
INSERT INTO `Car` (`vehicle_identification_number`,`model`, `year`, `color`,`manufacturer_ID`) VALUES ("HKNDGS7CU31E9Z7JW", "RAV4", 2018, "Silver", 132);
INSERT INTO `Car` (`vehicle_identification_number`,`model`, `year`, `color`,`manufacturer_ID`) VALUES ("DAM41UDN3CHU2WVF6", "V60", 2019, "Gray", 134);
INSERT INTO `Car` (`vehicle_identification_number`,`model`, `year`, `color`,`manufacturer_ID`) VALUES ("DAM41UDN3CHU2WVF6", "V60 Cross Country", 2019, "Gray", 134);

#Seeding countries
INSERT INTO `Country` (`name`) VALUES ("Afghanistan");
INSERT INTO `Country` (`name`) VALUES ("Albania");
INSERT INTO `Country` (`name`) VALUES ("Algeria");
INSERT INTO `Country` (`name`) VALUES ("Andorra");
INSERT INTO `Country` (`name`) VALUES ("Angola");
INSERT INTO `Country` (`name`) VALUES ("Antigua & Deps");
INSERT INTO `Country` (`name`) VALUES ("Argentina");
INSERT INTO `Country` (`name`) VALUES ("Armenia");
INSERT INTO `Country` (`name`) VALUES ("Australia");
INSERT INTO `Country` (`name`) VALUES ("Austria");
INSERT INTO `Country` (`name`) VALUES ("Azerbaijan");
INSERT INTO `Country` (`name`) VALUES ("Bahamas");
INSERT INTO `Country` (`name`) VALUES ("Bahrain");
INSERT INTO `Country` (`name`) VALUES ("Bangladesh");
INSERT INTO `Country` (`name`) VALUES ("Barbados");
INSERT INTO `Country` (`name`) VALUES ("Belarus");
INSERT INTO `Country` (`name`) VALUES ("Belgium");
INSERT INTO `Country` (`name`) VALUES ("Belize");
INSERT INTO `Country` (`name`) VALUES ("Benin");
INSERT INTO `Country` (`name`) VALUES ("Bhutan");
INSERT INTO `Country` (`name`) VALUES ("Bolivia");
INSERT INTO `Country` (`name`) VALUES ("Bosnia Herzegovina");
INSERT INTO `Country` (`name`) VALUES ("Botswana");
INSERT INTO `Country` (`name`) VALUES ("Brazil");
INSERT INTO `Country` (`name`) VALUES ("Brunei");
INSERT INTO `Country` (`name`) VALUES ("Bulgaria");
INSERT INTO `Country` (`name`) VALUES ("Burkina");
INSERT INTO `Country` (`name`) VALUES ("Burundi");
INSERT INTO `Country` (`name`) VALUES ("Cambodia");
INSERT INTO `Country` (`name`) VALUES ("Cameroon");
INSERT INTO `Country` (`name`) VALUES ("Canada");
INSERT INTO `Country` (`name`) VALUES ("Cape Verde");
INSERT INTO `Country` (`name`) VALUES ("Central African Rep");
INSERT INTO `Country` (`name`) VALUES ("Chad");
INSERT INTO `Country` (`name`) VALUES ("Chile");
INSERT INTO `Country` (`name`) VALUES ("China");
INSERT INTO `Country` (`name`) VALUES ("Colombia");
INSERT INTO `Country` (`name`) VALUES ("Comoros");
INSERT INTO `Country` (`name`) VALUES ("Congo");
INSERT INTO `Country` (`name`) VALUES ("Congo {Democratic Rep}");
INSERT INTO `Country` (`name`) VALUES ("Costa Rica");
INSERT INTO `Country` (`name`) VALUES ("Croatia");
INSERT INTO `Country` (`name`) VALUES ("Cuba");
INSERT INTO `Country` (`name`) VALUES ("Cyprus");
INSERT INTO `Country` (`name`) VALUES ("Czech Republic");
INSERT INTO `Country` (`name`) VALUES ("Denmark");
INSERT INTO `Country` (`name`) VALUES ("Djibouti");
INSERT INTO `Country` (`name`) VALUES ("Dominica");
INSERT INTO `Country` (`name`) VALUES ("Dominican Republic");
INSERT INTO `Country` (`name`) VALUES ("East Timor");
INSERT INTO `Country` (`name`) VALUES ("Ecuador");
INSERT INTO `Country` (`name`) VALUES ("Egypt");
INSERT INTO `Country` (`name`) VALUES ("El Salvador");
INSERT INTO `Country` (`name`) VALUES ("Equatorial Guinea");
INSERT INTO `Country` (`name`) VALUES ("Eritrea");
INSERT INTO `Country` (`name`) VALUES ("Estonia");
INSERT INTO `Country` (`name`) VALUES ("Ethiopia");
INSERT INTO `Country` (`name`) VALUES ("Fiji");
INSERT INTO `Country` (`name`) VALUES ("Finland");
INSERT INTO `Country` (`name`) VALUES ("France");
INSERT INTO `Country` (`name`) VALUES ("Gabon");
INSERT INTO `Country` (`name`) VALUES ("Gambia");
INSERT INTO `Country` (`name`) VALUES ("Georgia");
INSERT INTO `Country` (`name`) VALUES ("Germany");
INSERT INTO `Country` (`name`) VALUES ("Ghana");
INSERT INTO `Country` (`name`) VALUES ("Greece");
INSERT INTO `Country` (`name`) VALUES ("Grenada");
INSERT INTO `Country` (`name`) VALUES ("Guatemala");
INSERT INTO `Country` (`name`) VALUES ("Guinea");
INSERT INTO `Country` (`name`) VALUES ("Guinea-Bissau");
INSERT INTO `Country` (`name`) VALUES ("Guyana");
INSERT INTO `Country` (`name`) VALUES ("Haiti");
INSERT INTO `Country` (`name`) VALUES ("Honduras");
INSERT INTO `Country` (`name`) VALUES ("Hungary");
INSERT INTO `Country` (`name`) VALUES ("Iceland");
INSERT INTO `Country` (`name`) VALUES ("India");
INSERT INTO `Country` (`name`) VALUES ("Indonesia");
INSERT INTO `Country` (`name`) VALUES ("Iran");
INSERT INTO `Country` (`name`) VALUES ("Iraq");
INSERT INTO `Country` (`name`) VALUES ("Ireland {Republic}");
INSERT INTO `Country` (`name`) VALUES ("Israel");
INSERT INTO `Country` (`name`) VALUES ("Italy");
INSERT INTO `Country` (`name`) VALUES ("Ivory Coast");
INSERT INTO `Country` (`name`) VALUES ("Jamaica");
INSERT INTO `Country` (`name`) VALUES ("Japan");
INSERT INTO `Country` (`name`) VALUES ("Jordan");
INSERT INTO `Country` (`name`) VALUES ("Kazakhstan");
INSERT INTO `Country` (`name`) VALUES ("Kenya");
INSERT INTO `Country` (`name`) VALUES ("Kiribati");
INSERT INTO `Country` (`name`) VALUES ("Korea North");
INSERT INTO `Country` (`name`) VALUES ("Korea South");
INSERT INTO `Country` (`name`) VALUES ("Kosovo");
INSERT INTO `Country` (`name`) VALUES ("Kuwait");
INSERT INTO `Country` (`name`) VALUES ("Kyrgyzstan");
INSERT INTO `Country` (`name`) VALUES ("Laos");
INSERT INTO `Country` (`name`) VALUES ("Latvia");
INSERT INTO `Country` (`name`) VALUES ("Lebanon");
INSERT INTO `Country` (`name`) VALUES ("Lesotho");
INSERT INTO `Country` (`name`) VALUES ("Liberia");
INSERT INTO `Country` (`name`) VALUES ("Libya");
INSERT INTO `Country` (`name`) VALUES ("Liechtenstein");
INSERT INTO `Country` (`name`) VALUES ("Lithuania");
INSERT INTO `Country` (`name`) VALUES ("Luxembourg");
INSERT INTO `Country` (`name`) VALUES ("Macedonia");
INSERT INTO `Country` (`name`) VALUES ("Madagascar");
INSERT INTO `Country` (`name`) VALUES ("Malawi");
INSERT INTO `Country` (`name`) VALUES ("Malaysia");
INSERT INTO `Country` (`name`) VALUES ("Maldives");
INSERT INTO `Country` (`name`) VALUES ("Mali");
INSERT INTO `Country` (`name`) VALUES ("Malta");
INSERT INTO `Country` (`name`) VALUES ("Marshall Islands");
INSERT INTO `Country` (`name`) VALUES ("Mauritania");
INSERT INTO `Country` (`name`) VALUES ("Mauritius");
INSERT INTO `Country` (`name`) VALUES ("Mexico");
INSERT INTO `Country` (`name`) VALUES ("Micronesia");
INSERT INTO `Country` (`name`) VALUES ("Moldova");
INSERT INTO `Country` (`name`) VALUES ("Monaco");
INSERT INTO `Country` (`name`) VALUES ("Mongolia");
INSERT INTO `Country` (`name`) VALUES ("Montenegro");
INSERT INTO `Country` (`name`) VALUES ("Morocco");
INSERT INTO `Country` (`name`) VALUES ("Mozambique");
INSERT INTO `Country` (`name`) VALUES ("Myanmar, {Burma}");
INSERT INTO `Country` (`name`) VALUES ("Namibia");
INSERT INTO `Country` (`name`) VALUES ("Nauru");
INSERT INTO `Country` (`name`) VALUES ("Nepal");
INSERT INTO `Country` (`name`) VALUES ("Netherlands");
INSERT INTO `Country` (`name`) VALUES ("New Zealand");
INSERT INTO `Country` (`name`) VALUES ("Nicaragua");
INSERT INTO `Country` (`name`) VALUES ("Niger");
INSERT INTO `Country` (`name`) VALUES ("Nigeria");
INSERT INTO `Country` (`name`) VALUES ("Norway");
INSERT INTO `Country` (`name`) VALUES ("Oman");
INSERT INTO `Country` (`name`) VALUES ("Pakistan");
INSERT INTO `Country` (`name`) VALUES ("Palau");
INSERT INTO `Country` (`name`) VALUES ("Panama");
INSERT INTO `Country` (`name`) VALUES ("Papua New Guinea");
INSERT INTO `Country` (`name`) VALUES ("Paraguay");
INSERT INTO `Country` (`name`) VALUES ("Peru");
INSERT INTO `Country` (`name`) VALUES ("Philippines");
INSERT INTO `Country` (`name`) VALUES ("Poland");
INSERT INTO `Country` (`name`) VALUES ("Portugal");
INSERT INTO `Country` (`name`) VALUES ("Qatar");
INSERT INTO `Country` (`name`) VALUES ("Romania");
INSERT INTO `Country` (`name`) VALUES ("Russian Federation");
INSERT INTO `Country` (`name`) VALUES ("Rwanda");
INSERT INTO `Country` (`name`) VALUES ("St Kitts & Nevis");
INSERT INTO `Country` (`name`) VALUES ("St Lucia");
INSERT INTO `Country` (`name`) VALUES ("Saint Vincent & the Grenadines");
INSERT INTO `Country` (`name`) VALUES ("Samoa");
INSERT INTO `Country` (`name`) VALUES ("San Marino");
INSERT INTO `Country` (`name`) VALUES ("Sao Tome & Principe");
INSERT INTO `Country` (`name`) VALUES ("Saudi Arabia");
INSERT INTO `Country` (`name`) VALUES ("Senegal");
INSERT INTO `Country` (`name`) VALUES ("Serbia");
INSERT INTO `Country` (`name`) VALUES ("Seychelles");
INSERT INTO `Country` (`name`) VALUES ("Sierra Leone");
INSERT INTO `Country` (`name`) VALUES ("Singapore");
INSERT INTO `Country` (`name`) VALUES ("Slovakia");
INSERT INTO `Country` (`name`) VALUES ("Slovenia");
INSERT INTO `Country` (`name`) VALUES ("Solomon Islands");
INSERT INTO `Country` (`name`) VALUES ("Somalia");
INSERT INTO `Country` (`name`) VALUES ("South Africa");
INSERT INTO `Country` (`name`) VALUES ("South Sudan");
INSERT INTO `Country` (`name`) VALUES ("Spain");
INSERT INTO `Country` (`name`) VALUES ("Sri Lanka");
INSERT INTO `Country` (`name`) VALUES ("Sudan");
INSERT INTO `Country` (`name`) VALUES ("Suriname");
INSERT INTO `Country` (`name`) VALUES ("Swaziland");
INSERT INTO `Country` (`name`) VALUES ("Sweden");
INSERT INTO `Country` (`name`) VALUES ("Switzerland");
INSERT INTO `Country` (`name`) VALUES ("Syria");
INSERT INTO `Country` (`name`) VALUES ("Taiwan");
INSERT INTO `Country` (`name`) VALUES ("Tajikistan");
INSERT INTO `Country` (`name`) VALUES ("Tanzania");
INSERT INTO `Country` (`name`) VALUES ("Thailand");
INSERT INTO `Country` (`name`) VALUES ("Togo");
INSERT INTO `Country` (`name`) VALUES ("Tonga");
INSERT INTO `Country` (`name`) VALUES ("Trinidad & Tobago");
INSERT INTO `Country` (`name`) VALUES ("Tunisia");
INSERT INTO `Country` (`name`) VALUES ("Turkey");
INSERT INTO `Country` (`name`) VALUES ("Turkmenistan");
INSERT INTO `Country` (`name`) VALUES ("Tuvalu");
INSERT INTO `Country` (`name`) VALUES ("Uganda");
INSERT INTO `Country` (`name`) VALUES ("Ukraine");
INSERT INTO `Country` (`name`) VALUES ("United Arab Emirates");
INSERT INTO `Country` (`name`) VALUES ("United Kingdom");
INSERT INTO `Country` (`name`) VALUES ("United States");
INSERT INTO `Country` (`name`) VALUES ("Uruguay");
INSERT INTO `Country` (`name`) VALUES ("Uzbekistan");
INSERT INTO `Country` (`name`) VALUES ("Vanuatu");
INSERT INTO `Country` (`name`) VALUES ("Vatican City");
INSERT INTO `Country` (`name`) VALUES ("Venezuela");
INSERT INTO `Country` (`name`) VALUES ("Vietnam");
INSERT INTO `Country` (`name`) VALUES ("Yemen");
INSERT INTO `Country` (`name`) VALUES ("Zambia");
INSERT INTO `Country` (`name`) VALUES ("Zimbabwe");

#Seeding Address
INSERT INTO `Address` (`address`, `city`, `state/province`, `zip/postal_code`, `country_ID`) VALUES ("Paseo de la Chopera, 14", "Madrid", "Madrid", 28045, 164);
INSERT INTO `Address` (`address`, `city`, `state/province`, `zip/postal_code`, `country_ID`) VALUES ("120 SW 8th St", "Miami", "Florida", 33130, 187);
INSERT INTO `Address` (`address`, `city`, `state/province`, `zip/postal_code`, `country_ID`) VALUES ("40 Rue du Colisée", "Paris", "Île-de-France", 75008, 60);

#Seeding Customer
INSERT INTO `Customer` (`customer_ID`, `name`, `phone_number`, `address_ID`) VALUES (10001, "Pablo Picasso", "+34 636 17 63 82", 1);
INSERT INTO `Customer` (`customer_ID`, `name`, `phone_number`, `address_ID`) VALUES (20001, "Abraham Lincoln¡", "+1 305 907 7086", 2);
INSERT INTO `Customer` (`customer_ID`, `name`, `phone_number`, `address_ID`) VALUES (30001, "Napoléon Bonaparte", "+33 1 79 75 40 00", 3);

#Seeding Sales_Person
INSERT INTO `Sales_Person` (`staff_ID`, `name`, `store`) VALUES (1,	"Petey Cruiser", "Madrid");
INSERT INTO `Sales_Person` (`staff_ID`, `name`, `store`) VALUES (2,	"Anna Sthesia", "Barcelona");
INSERT INTO `Sales_Person` (`staff_ID`, `name`, `store`) VALUES (3,	"Paul Molive", "Berlin");
INSERT INTO `Sales_Person` (`staff_ID`, `name`, `store`) VALUES (4,	"Gail Forcewin", "Paris");
INSERT INTO `Sales_Person` (`staff_ID`, `name`, `store`) VALUES (5,	"Paige Turner", "Mimia");
INSERT INTO `Sales_Person` (`staff_ID`, `name`, `store`) VALUES (6,	"Bob Frapples", "Mexico City");
INSERT INTO `Sales_Person` (`staff_ID`, `name`, `store`) VALUES (7,	"Walter Melon", "Amsterdam");
INSERT INTO `Sales_Person` (`staff_ID`, `name`, `store`) VALUES (8,	"Shonda Leer", "São Paulo");

#Seeding Invoices
INSERT INTO `Invoice` (`invoice_number`, `invoice_date`, `car_ID`, `customer_ID`, `sales_person_ID`) VALUES ("852399038", 20180822,1, 2, 14);
INSERT INTO `Invoice` (`invoice_number`, `invoice_date`, `car_ID`, `customer_ID`, `sales_person_ID`) VALUES ("731166526", 20181231,4, 1, 15);
INSERT INTO `Invoice` (`invoice_number`, `invoice_date`, `car_ID`, `customer_ID`, `sales_person_ID`) VALUES ("271135104", 20190122,3, 3, 18);